# Generated by Django 2.1.5 on 2019-01-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='armor')),
                ('defense', models.PositiveSmallIntegerField(verbose_name='defense')),
                ('soak', models.PositiveSmallIntegerField(verbose_name='soak')),
                ('encumberment', models.PositiveSmallIntegerField(verbose_name='encumberment')),
                ('hardpoint', models.PositiveSmallIntegerField(verbose_name='hard point')),
                ('price', models.PositiveSmallIntegerField(verbose_name='price')),
                ('rarity', models.PositiveSmallIntegerField(verbose_name='rarity')),
                ('index', models.CharField(max_length=80, verbose_name='index')),
            ],
            options={
                'verbose_name': 'armor',
                'verbose_name_plural': 'armors',
                'ordering': ('name', 'category'),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='armor')),
                ('price', models.PositiveSmallIntegerField(verbose_name='price')),
                ('encumberment', models.PositiveSmallIntegerField(verbose_name='encumberment')),
                ('hardpoint', models.PositiveSmallIntegerField(verbose_name='hard point required')),
                ('rarity', models.PositiveSmallIntegerField(verbose_name='rarity')),
                ('index', models.CharField(max_length=80, verbose_name='index')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachements',
                'ordering': ('name', 'category'),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='book')),
                ('system', models.CharField(max_length=80, verbose_name='system')),
                ('key', models.CharField(max_length=12, verbose_name='product key')),
                ('initials', models.CharField(max_length=12, verbose_name='initials')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('price', models.PositiveSmallIntegerField(verbose_name='price')),
                ('encumberment', models.PositiveSmallIntegerField(verbose_name='encumberment')),
                ('rarity', models.PositiveSmallIntegerField(verbose_name='rarity')),
                ('index', models.CharField(max_length=80, verbose_name='index')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Gear_Category', to='core.Category')),
            ],
            options={
                'verbose_name': 'gear',
                'verbose_name_plural': 'gears',
                'ordering': ('name', 'category'),
            },
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='armor')),
                ('silhouette', models.PositiveSmallIntegerField(verbose_name='silhouette')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='speed')),
                ('handling', models.IntegerField(verbose_name='handling')),
                ('armor', models.PositiveSmallIntegerField(verbose_name='armor')),
                ('defense', models.CharField(max_length=20, verbose_name='defense')),
                ('hull', models.PositiveSmallIntegerField(verbose_name='hull trauma')),
                ('strain', models.PositiveSmallIntegerField(verbose_name='system strain')),
                ('manufacturer', models.CharField(max_length=60, verbose_name='manufacturer')),
                ('hd_nc', models.CharField(max_length=20, verbose_name='hyperdrive/navicomputer')),
                ('crew', models.PositiveSmallIntegerField(verbose_name='crew')),
                ('encumberment', models.PositiveSmallIntegerField(verbose_name='encumberment')),
                ('passenger', models.PositiveSmallIntegerField(verbose_name='passenger')),
                ('hardpoint', models.PositiveSmallIntegerField(verbose_name='hard point')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='cost')),
                ('weapon', models.CharField(max_length=80, verbose_name='weapon')),
                ('rarity', models.PositiveSmallIntegerField(verbose_name='rarity')),
                ('index', models.CharField(max_length=80, verbose_name='index')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Starship_Category', to='core.Category')),
            ],
            options={
                'verbose_name': 'starship',
                'verbose_name_plural': 'starships',
                'ordering': ('name', 'category'),
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='armor')),
                ('silhouette', models.PositiveSmallIntegerField(verbose_name='silhouette')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='speed')),
                ('handling', models.IntegerField(verbose_name='handling')),
                ('armor', models.PositiveSmallIntegerField(verbose_name='armor')),
                ('defense', models.CharField(max_length=20, verbose_name='defense')),
                ('hull', models.PositiveSmallIntegerField(verbose_name='hull trauma')),
                ('strain', models.PositiveSmallIntegerField(verbose_name='system strain')),
                ('manufacturer', models.CharField(max_length=60, verbose_name='manufacturer')),
                ('crew', models.PositiveSmallIntegerField(verbose_name='crew')),
                ('encumberment', models.PositiveSmallIntegerField(verbose_name='encumberment')),
                ('passenger', models.PositiveSmallIntegerField(verbose_name='passenger')),
                ('hardpoint', models.PositiveSmallIntegerField(verbose_name='hard point')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='cost')),
                ('weapon', models.CharField(max_length=80, verbose_name='weapon')),
                ('rarity', models.PositiveSmallIntegerField(verbose_name='rarity')),
                ('index', models.CharField(max_length=80, verbose_name='index')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Vehicule_Category', to='core.Category')),
            ],
            options={
                'verbose_name': 'vehicule',
                'verbose_name_plural': 'vehicules',
                'ordering': ('name', 'category'),
            },
        ),
        migrations.CreateModel(
            name='VehiculeAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='armor')),
                ('price', models.PositiveSmallIntegerField(verbose_name='price')),
                ('hardpoint', models.PositiveSmallIntegerField(verbose_name='hard point required')),
                ('rarity', models.PositiveSmallIntegerField(verbose_name='rarity')),
                ('index', models.CharField(max_length=80, verbose_name='index')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Vehicule_Attachment_Category', to='core.Category')),
            ],
            options={
                'verbose_name': 'vehicule attachment',
                'verbose_name_plural': 'vehicules attachements',
                'ordering': ('name', 'category'),
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('skill', models.CharField(max_length=80, verbose_name='skill')),
                ('damage', models.PositiveSmallIntegerField(verbose_name='damage')),
                ('critical', models.PositiveSmallIntegerField(verbose_name='critical')),
                ('rangemax', models.CharField(max_length=80, verbose_name='range')),
                ('encumberment', models.PositiveSmallIntegerField(verbose_name='encumberment')),
                ('hardpoint', models.PositiveSmallIntegerField(verbose_name='hard point')),
                ('price', models.PositiveSmallIntegerField(verbose_name='price')),
                ('rarity', models.PositiveSmallIntegerField(verbose_name='rarity')),
                ('special', models.CharField(max_length=180, verbose_name='range')),
                ('index', models.CharField(max_length=80, verbose_name='index')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Weapon_Category', to='core.Category')),
            ],
            options={
                'verbose_name': 'weapon',
                'verbose_name_plural': 'weapons',
                'ordering': ('name', 'category'),
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Attachment_Category', to='core.Category'),
        ),
        migrations.AddField(
            model_name='armor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Armor_Category', to='core.Category'),
        ),
    ]
