# Generated by Django 2.1.5 on 2019-01-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Quality')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('ranked', models.BooleanField(verbose_name='Ranked')),
                ('effect', models.TextField(verbose_name='Effect')),
                ('index', models.CharField(max_length=80, verbose_name='index')),
            ],
        ),
        migrations.AlterModelOptions(
            name='armor',
            options={'ordering': ('name',), 'verbose_name': 'armor', 'verbose_name_plural': 'armors'},
        ),
        migrations.RemoveField(
            model_name='armor',
            name='category',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='special',
            field=models.CharField(max_length=180, verbose_name='special'),
        ),
    ]
