# Generated by Django 2.1.5 on 2019-01-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190124_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('name', 'system', 'translate'), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='qualities',
            options={'ordering': ('name',), 'verbose_name': 'Quality', 'verbose_name_plural': 'Qualities'},
        ),
        migrations.AddField(
            model_name='book',
            name='translate',
            field=models.BooleanField(default=False, verbose_name='tanslate'),
        ),
    ]
