# Generated by Django 2.1.5 on 2019-01-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190127_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='defense_close',
        ),
        migrations.RemoveField(
            model_name='armor',
            name='defense_dist',
        ),
        migrations.AddField(
            model_name='armor',
            name='defense',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='defense'),
        ),
        migrations.AddField(
            model_name='armor',
            name='legal',
            field=models.BooleanField(default=True, verbose_name='legal'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='legal',
            field=models.BooleanField(default=True, verbose_name='legal'),
        ),
        migrations.AddField(
            model_name='gear',
            name='legal',
            field=models.BooleanField(default=True, verbose_name='legal'),
        ),
        migrations.AddField(
            model_name='starship',
            name='legal',
            field=models.BooleanField(default=True, verbose_name='legal'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='legal',
            field=models.BooleanField(default=True, verbose_name='legal'),
        ),
        migrations.AddField(
            model_name='vehiculeattachment',
            name='legal',
            field=models.BooleanField(default=True, verbose_name='legal'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='legal',
            field=models.BooleanField(default=True, verbose_name='legal'),
        ),
    ]
