# Generated by Django 2.1.5 on 2019-01-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190127_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='skill')),
                ('name_fr', models.CharField(max_length=30, null=True, verbose_name='skill')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='armor',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='armor',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='book'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='book'),
        ),
        migrations.AddField(
            model_name='book',
            name='system_en',
            field=models.CharField(max_length=80, null=True, verbose_name='system'),
        ),
        migrations.AddField(
            model_name='book',
            name='system_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='system'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='gear',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='gear',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='qualities',
            name='effect_en',
            field=models.TextField(null=True, verbose_name='Effect'),
        ),
        migrations.AddField(
            model_name='qualities',
            name='effect_fr',
            field=models.TextField(null=True, verbose_name='Effect'),
        ),
        migrations.AddField(
            model_name='qualities',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='qualities',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='starship',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='starship',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='starship',
            name='weapon_en',
            field=models.CharField(max_length=80, null=True, verbose_name='weapon'),
        ),
        migrations.AddField(
            model_name='starship',
            name='weapon_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='weapon'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='weapon_en',
            field=models.CharField(max_length=80, null=True, verbose_name='weapon'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='weapon_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='weapon'),
        ),
        migrations.AddField(
            model_name='vehiculeattachment',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='vehiculeattachment',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='armor'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='name'),
        ),
    ]
