# Generated by Django 2.1.5 on 2019-01-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190128_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='system_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='effect_en',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='starship',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='starship',
            name='weapon_en',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='weapon_en',
        ),
        migrations.RemoveField(
            model_name='vehiculeattachment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='name_en',
        ),
    ]
